blank_issues_enabled: false
contact_links:
  - name: Red40 Development Discord
    url: https://discord.gg/ShMFbNQuqy
    about: Ask questions, receive support, and discuss with the community in our Discord server.
