name: "Discord Release Notification"

on:
  release:
    types: [published]
jobs:
  discord-release:
    uses: Red40-Development/red40_repo_sync/.github/workflows/reusable-discord-release.yml@v1
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
